const constants = {
    STATE_ATON: {
        "AL": "Alabama",
        "AK": "Alaska",
        "AS": "American Samoa",
        "AZ": "Arizona",
        "AR": "Arkansas",
        "CA": "California",
        "CO": "Colorado",
        "CT": "Connecticut",
        "DE": "Delaware",
        "DC": "District of Columbia",
        "FM": "Federated States of Micronesia",
        "FL": "Florida",
        "GA": "Georgia",
        "GU": "Guam",
        "HI": "Hawaii",
        "ID": "Idaho",
        "IL": "Illinois",
        "IN": "Indiana",
        "IA": "Iowa",
        "KS": "Kansas",
        "KY": "Kentucky",
        "LA": "Louisiana",
        "ME": "Maine",
        "MH": "Marshall Islands",
        "MD": "Maryland",
        "MA": "Massachusetts",
        "MI": "Michigan",
        "MN": "Minnesota",
        "MS": "Mississippi",
        "MO": "Missouri",
        "MT": "Montana",
        "NE": "Nebraska",
        "NV": "Nevada",
        "NH": "New Hampshire",
        "NJ": "New Jersey",
        "NM": "New Mexico",
        "NY": "New York",
        "NC": "North Carolina",
        "ND": "North Dakota",
        "MP": "Northern Mariana Islands",
        "OH": "Ohio",
        "OK": "Oklahoma",
        "OR": "Oregon",
        "PW": "Palau",
        "PA": "Pennsylvania",
        "PR": "Puerto Rico",
        "RI": "Rhode Island",
        "SC": "South Carolina",
        "SD": "South Dakota",
        "TN": "Tennessee",
        "TX": "Texas",
        "UT": "Utah",
        "VT": "Vermont",
        "VI": "Virgin Islands",
        "VA": "Virginia",
        "WA": "Washington",
        "WV": "West Virginia",
        "WI": "Wisconsin",
        "WY": "Wyoming"
    },

    CANDIDATE_NAMES: {
        'Allen, Jonathan': 'Allen, Jonathan E.',
        'Amondson, Gene': 'Amondson, Gene C.',
        'Anderson, Rocky': 'Anderson, Ross C.',
        'Anderson, Ross': 'Anderson, Ross C.',
        'Anderson, Ross "Rocky" C.': 'Anderson, Ross C.',
        'Anderson, Ross C. "Rocky"': 'Anderson, Ross C.',
        'Anderson, Ross C. (Rocky)': 'Anderson, Ross C.',
        'Baldwin, Charles O. "Chuck"': 'Baldwin, Charles O.',
        'Baldwin, Charles Obadiah': 'Baldwin, Charles O.',
        'Baldwin, Chuck': 'Baldwin, Charles O.',
        'Barnett, Andre': 'Barnett, Andre N.',
        'Barr, "Bob"': 'Barr, Bob',
        'Barr, Roseanne': 'Barr, Roseanne C.',
        'Bone, Lawson': 'Bone, Lawson M.',
        'Bone, Lawson Mitchell': 'Bone, Lawson M.',
        'Boss, Jeffrey "Jeff"': 'Boss, Jeffrey',
        'Boss, Jeff': 'Boss, Jeffrey',
        'Brown, Walt': 'Brown, Walter F.',
        'Brown, Walter': 'Brown, Walter F.',
        'Brown, Walter F. "Walt"': 'Brown, Walter F.',
        'Brown, Walter Frederick': 'Brown, Walter F.',
        'Bush, George': 'Bush, George W.',
        'Bush, George Walker': 'Bush, George W.',
        'Byrne, David': 'Byrne, David C.',
        'Calero, Roger': 'Calero, Róger',
        'Chehade, Paul / McAllister, Steve': 'Chehade, Paul',
        'Clinton, Hilary': 'Clinton, Hillary',
        'Clymer, Jim': 'Clymer, James',
        'Cobb, David': 'Cobb, David K.',
        'Cobb, David Keith': 'Cobb, David K.',
        'Duncan, Richard': 'Duncan, Richard A.',
        'Durham, Stephen': 'Durham, Stephen G.',
        'Durham, Stephen / Lopez, Christina': 'Durham, Stephen G.',
        'Glean, Joseph A. / Darlene Herleikson': 'Glean, Joseph A.',
        'Glean, Joseph A. / Jamie Johnson': 'Glean, Joseph A.',
        'Goode, Virgil': 'Goode, Virgil H.',
        'Goode, Virgil / Clymer, Jim': 'Goode, Virgil H.',
        'Goode, Virgil H., Jr.': 'Goode, Virgil H.',
        'Goode, Virgil, Jr.': 'Goode, Virgil H.',
        'Harris, James': 'Harris, James E.',
        'Heupel, RaeDeen': 'Heupel, RaeDeen R.',
        'Hobbs, Ron': 'Hobbs, Ronald G.',
        'Hoefling, Tom': 'Hoefling, Thomas',
        'Hoefling, Tom / Ellis, Jonathan': 'Hoefling, Thomas',
        'Johnson, Gary': 'Johnson, Gary E.',
        'Kennedy, John': 'Kennedy, John J.',
        'Kennedy, John Joseph': 'Kennedy, John J.',
        'Kerry, John': 'Kerry, John F.',
        'Keyes, Alan': 'Keyes, Alan L.',
        'Keyes, Alan Lee': 'Keyes, Alan L.',
        'Kucinich, Dennis': 'Kucinich, Dennis J.',
        'McCain, John': 'McCain, John S.',
        'McCain, John Sidney, III': 'McCain, John S.',
        'McKinney, Cynthia': 'McKinney, Cynthia A.',
        'McKinney, Cynthia Ann': 'McKinney, Cynthia A.',
        'Moore, Frank': 'Moore, Frank J.',
        'Moore, Frank James': 'Moore, Frank J.',
        'Obama, Barack': 'Obama, Barack H.',
        'Obama, Barack Hussein': 'Obama, Barack H.',
        'Parker, John Thompson': 'Parker, John T.',
        'Parker, John': 'Parker, John T.',
        'Paul, "Ron"': 'Paul, Ronald E.',
        'Paul, Ron': 'Paul, Ronald E.',
        'Peroutka, Michael': 'Peroutka, Michael A.',
        'Peroutka, Michael Anthony': 'Peroutka, Michael A.',
        'Prokopich, Barbara': 'Prokopich, Barbara A.',
        'Reed, Jill': 'Reed, Jill A.',
        'Reed, Jill / Cary, Tom': 'Reed, Jill A.',
        'Reed, Jill Ann': 'Reed, Jill A.',
        'Reid, Jill': 'Reed, Jill A.',
        'Roth, Cecil': 'Roth, Cecil J.',
        'Roth, Cecil James': 'Roth, Cecil J.',
        'Stein, Jill A.': 'Stein, Jill',
        'Stein, Jill E.': 'Stein, Jill',
        'Terry, Randall': 'Terry, Randall A.',
        'Tittle, Sheila "Samm"': 'Tittle, Sheila',
        "Tittle, Sheila 'Samm'": 'Tittle, Sheila',
        'White, Jerry': 'White, Jerome S.',
        'White, Jerry / Scherrer, Phyllis': 'White, Jerome S.'
    },

    EC_2004: {
        'Alabama':              9,
        'Alaska':               3,
        'Arizona':              10,
        'Arkansas':             6,
        'California':           55,
        'Colorado':             9,
        'Connecticut':          7,
        'Delaware':             3,
        'District of Columbia': 3,
        'Florida':              27,
        'Georgia':              15,
        'Hawaii':               4,
        'Idaho':                4,
        'Illinois':             21,
        'Indiana':              11,
        'Iowa':                 7,
        'Kansas':               6,
        'Kentucky':             8,
        'Louisiana':            9,
        'Maine':                4,
        'Maryland':             10,
        'Massachusetts':        12,
        'Michigan':             17,
        'Minnesota':            10,
        'Mississippi':          6,
        'Missouri':             11,
        'Montana':              3,
        'Nebraska':             5,
        'Nevada':               5,
        'New Hampshire':        4,
        'New Jersey':           15,
        'New Mexico':           5,
        'New York':             31,
        'North Carolina':       15,
        'North Dakota':         3,
        'Ohio':                 20,
        'Oklahoma':             7,
        'Oregon':               7,
        'Pennsylvania':         21,
        'Rhode Island':         4,
        'South Carolina':       8,
        'South Dakota':         3,
        'Tennessee':            11,
        'Texas':                34,
        'Utah':                 5,
        'Vermont':              3,
        'Virginia':             13,
        'Washington':           11,
        'West Virginia':        5,
        'Wisconsin':            10,
        'Wyoming':              3
    },

    EC_2012: {
        'Alabama':              9,
        'Alaska':               3,
        'Arizona':              11,
        'Arkansas':             6,
        'California':           55,
        'Colorado':             9,
        'Connecticut':          7,
        'Delaware':             3,
        'District of Columbia': 3,
        'Florida':              29,
        'Georgia':              16,
        'Hawaii':               4,
        'Idaho':                4,
        'Illinois':             20,
        'Indiana':              11,
        'Iowa':                 6,
        'Kansas':               6,
        'Kentucky':             8,
        'Louisiana':            8,
        'Maine':                4,
        'Maryland':             10,
        'Massachusetts':        11,
        'Michigan':             16,
        'Minnesota':            10,
        'Mississippi':          6,
        'Missouri':             10,
        'Montana':              3,
        'Nebraska':             5,
        'Nevada':               6,
        'New Hampshire':        4,
        'New Jersey':           14,
        'New Mexico':           5,
        'New York':             29,
        'North Carolina':       15,
        'North Dakota':         3,
        'Ohio':                 18,
        'Oklahoma':             7,
        'Oregon':               7,
        'Pennsylvania':         20,
        'Rhode Island':         4,
        'South Carolina':       9,
        'South Dakota':         3,
        'Tennessee':            11,
        'Texas':                38,
        'Utah':                 6,
        'Vermont':              3,
        'Virginia':             13,
        'Washington':           12,
        'West Virginia':        5,
        'Wisconsin':            10,
        'Wyoming':              3
    },

    MAINE_2004: {
        'Bush, George W.': 0,
        'Kerry, John F.': 4
    },

    NEBRASKA_2004: {
        'Bush, George W.': 5,
        'Kerry, John F.': 0
    },

    MAINE_2008: {
        'McCain, John S.': 0,
        'Obama, Barack H.': 4
    },

    NEBRASKA_2008: {
        'McCain, John S.': 4,
        'Obama, Barack H.': 1
    },

    MAINE_2012: {
        'Romney, Mitt': 0,
        'Obama, Barack H.': 4
    },

    NEBRASKA_2012: {
        'Romney, Mitt': 5,
        'Obama, Barack H.': 0
    },

    CANDIDATES: {
        '2004': { 'Democratic': 'Kerry, John F.', 'Republican': 'Bush, George W.' },
        '2008': { 'Democratic': 'Obama, Barack H.', 'Republican': 'McCain, John S.' },
        '2012': { 'Democratic': 'Obama, Barack H.', 'Republican': 'Romney, Mitt' }
    }
};

constants.STATE_NTOA = _.invert(constants.STATE_ATON);